

IF OBJECT_ID('mi_ATM945_ACOI.dbo.dat_Claims_p', 'U') IS NOT NULL
DROP TABLE mi_ATM945_ACOI.dbo.dat_Claims_p;

use mi_ATM945_ACOI
go
exec sp_rename 'dbo.dat_Claims', 'dat_Claims_p';  



SELECT 
	[*===	DATES ===*]
	,[INCURRED_MONTH_START_DATE]
	,[INCURRED_YEAR_AND_MONTH]
	,[INCURRED_YEAR]
	,[INCURRED_CAL_QUARTER]
	,[INCURRED_FISCAL_YEAR]
	,[INCURRED_FISCAL_QUARTER]
	,[FROM_DATE]
	,[TO_DATE]
	,[PAID_MONTH_START_DATE]
	,[PAID_YEAR_AND_MONTH]
	,[PAID_YEAR]
	,[PAID_CAL_QUARTER]
	,[PAID_FISCAL_YEAR]
	,[PAID_FISCAL_QUARTER]
	,[PAID_DATE]
	,[ADM_DATE]
	,[DIS_DATE]
	,[*=== KEYS/CLAIM INFO ===*]
	,[CLAIM_IN_NETWORK]
	,[CLAIM_ID_WITH_CLAIM_SUFFIX]
	,[CLAIM_ID]
	,[CLAIM_SUFFIX]
	,[CLAIM_ID_KEY]
	,[CS_CLAIM_ID_KEY]
	,[FACILITY_CLAIM_ID_KEY]
	,[CONT_STAY_CLAIM_ID_W_SUFFIX]
	,[CONT_STAY_CLAIM_ID]
	,[CONT_STAY_CLAIM_CLAIM_SUFFIX]
	,[SERVICES_KEY]
	,[MI_POST_DATE]
	,[CLAIM_ENTRY_DATE]
	,[CLAIM_REC_DATE]
	,[SV_LINE]
	,[FORM_TYPE]
	,[SV_STAT]
	,[SV_STAT_AND_DESC]
	,[CHK_NUM]
	,[POS]
	,[DIS_STAT]
	,[BEN_PKG_KEY]
	,[*=== MEMBER/ELIGIBILITY ===*]
	,[MEMBER_ID]
	,[MEMBER_ID_ENCRYPTED]
	,[MEMBER_KEY]
	,[*=== SERVICE CODES ===*]
	,[PROC_CODE]
	,[PROC_DESC]
	,[PROC_CODE_AND_DESC]
	,[PROC_CODE_FAMILY_ID]
	,[PROC_CODE_FAMILY_LEVEL_1]
	,[PROC_CODE_FAMILY_LEVEL_2]
	,[PROC_CODE_FAMILY_LEVEL_3]
	,[PROC_CODE_AHRQ_CCS]
	,[CPT_MOD]
	,[TOS]
	,[CLIENT_MS_DRG_CODE]
	,[CLIENT_MS_DRG_DESC]
	,[CLIENT_MS_DRG_CODE_AND_DESC]
	,[MI_MS_DRG_CODE]
	,[MI_MS_DRG_DESC]
	,[MI_MS_DRG_CODE_AND_DESC]
	,[REV_CODE]
	,[REV_DESC]
	,[REV_CODE_AND_DESC]
	,[UB_BILL_TYPE]
	,[UB_BILL_FACTYPE_DESC]
	,[ICD_PROC_01_PRINCIPLE]
	,[ICD_PROC_DESC_PRI]
	,[ICD_PROC_02]
	,[ICD_PROC_03]
	,[ICD_PROC_04]
	,[ICD_PROC_05]
	,[ICD_PROC_06]
	,[ICD_PROC_07]
	,[ICD_PROC_08]
	,[ICD_PROC_09]
	,[ICD_PROC_10]
	,[ICD_PROC_11]
	,[ICD_PROC_12]
	,[ICD_PROC_13]
	,[ICD_PROC_14]
	,[ICD_PROC_15]
	,[ICD_PROC_16]
	,[ICD_PROC_17]
	,[ICD_PROC_18]
	,[ICD_PROC_19]
	,[ICD_PROC_20]
	,[ICD_PROC_21]
	,[ICD_PROC_22]
	,[ICD_PROC_23]
	,[ICD_PROC_24]
	,[ICD_PROC_25]
	,[ICD_PROC_26]
	,[ICD_PROC_27]
	,[ICD_PROC_28]
	,[ICD_PROC_29]
	,[ICD_PROC_30]
	,[*=== DIAGNOSES ===*]
	,[ICD_10_OR_HIGHER]
	,[ICD_DIAG_01_PRIMARY]
	,[ICD_DIAG_DESC_PRIMARY]
	,[ICD_DIAG_CODE_AND_DESC_PRI]
	,[ICD_DIAG_ROLLUP_DESC_PRI]
	,[ICD_DX_AHRQ_CCS_L1]
	,[ICD_DX_AHRQ_CCS_L2]
	,[ICD9_DX_AHRQ_CCS_L3]
	,[ICD10_DX_AHRQ_CCS_L3]
	,[ICD_DIAG_02]
	,[ICD_DIAG_03]
	,[ICD_DIAG_04]
	,[ICD_DIAG_05]
	,[ICD_DIAG_06]
	,[ICD_DIAG_07]
	,[ICD_DIAG_08]
	,[ICD_DIAG_09]
	,[ICD_DIAG_10]
	,[ICD_DIAG_11]
	,[ICD_DIAG_12]
	,[ICD_DIAG_13]
	,[ICD_DIAG_14]
	,[ICD_DIAG_15]
	,[ICD_DIAG_16]
	,[ICD_DIAG_17]
	,[ICD_DIAG_18]
	,[ICD_DIAG_19]
	,[ICD_DIAG_20]
	,[ICD_DIAG_21]
	,[ICD_DIAG_22]
	,[ICD_DIAG_23]
	,[ICD_DIAG_24]
	,[ICD_DIAG_25]
	,[ICD_DIAG_26]
	,[ICD_DIAG_27]
	,[ICD_DIAG_28]
	,[ICD_DIAG_29]
	,[ICD_DIAG_30]
	,[*=== SERVICE PROVIDER ===*]
	,[ATT_PROV_KEY]
	,[ATT_PROV_ID]
	,[ATTENDING_MI_SPECIALTY]
	,[ATT_HCG_PRIMARY_CARE]
	,[BILL_PROV_KEY]
	,[BILL_PROV_ID]
	,[CONTRACT]
	,[*=== AMOUNTS ===*]
	,[SV_UNITS]
	,[AMT_BILLED]
	,[AMT_ALLOWED]
	,[AMT_ALLOWED_STAT]
	,[AMT_PAID]
	,[AMT_DEDUCT]
	,[AMT_COINS]
	,[AMT_COPAY]
	,[AMT_COB]
	,[AMT_BILLED_DISC]
	,[AMT_ALLOWED_DISC]
	,[AMT_WITHHOLD]
	,[AMT_DISALLOWED]
	,[AMT_MAXIMUM]
	,[AMT_HRA]
	,[*=== MILLIMAN HCG ===*]
	,case when c.[CUR_CLM_UNIQ_ID] is null then [HCG_SETTING] else '5. Ancillary' end as [HCG_SETTING]
	,case when c.[CUR_CLM_UNIQ_ID] is null then [HCG_MR_LINE] else 'P82b' end as [HCG_MR_LINE]
	,case when c.[CUR_CLM_UNIQ_ID] is null then [HCG_MR_LINE_DESC] else 'OTH Private Duty Nursing/Home Health - Hospice' end as [HCG_MR_LINE_DESC]
	,case when c.[CUR_CLM_UNIQ_ID] is null then [HCG_MR_LINE_GROUP] else 'OTH' end as [HCG_MR_LINE_GROUP]
	,case when c.[CUR_CLM_UNIQ_ID] is null then [HCG_MR_LINE_CODE_AND_DESC] else 'P82b - OTH Private Duty Nursing/Home Health - Hospice' end as [HCG_MR_LINE_CODE_AND_DESC] 
	,case when c.[CUR_CLM_UNIQ_ID] is null then [HCG_MR_LINE_ROLLUP] else 'P82' end as [HCG_MR_LINE_ROLLUP]
	,case when c.[CUR_CLM_UNIQ_ID] is null then [HCG_MR_LINE_ROLLUP_DESC] else 'Private Duty Nursing/Home Health' end as [HCG_MR_LINE_ROLLUP_DESC]
	,case when c.[CUR_CLM_UNIQ_ID] is null then [MR_LINE_CASE_KEY] else 648 end as [MR_LINE_CASE_KEY]
	,[HCG_VERSION]
	,[HCG_YEAR]
	,[CASES]
	,case when c.[CUR_CLM_UNIQ_ID] is null then [UTILS] else [MR_ADMITS_CASES_RAW] end as [UTILS]
	,[CASE_SOURCE]
	,[CASE_BASIS]
	,case when c.[CUR_CLM_UNIQ_ID] is null then [UTIL_SOURCE] else 'MR_Admits_Cases' end as [UTIL_SOURCE]
	,case when c.[CUR_CLM_UNIQ_ID] is null then [UTIL_BASIS] else 'visits' end as [UTIL_BASIS]
	,[MR_ADMITS_CASES_RAW]
	,[MR_UNITS_DAYS_RAW]
	,[MR_PROCS_RAW]
	,[*=== WASTE CALCULATOR ===*]
	,[WASTE_CAT]
	,[WASTE_HEADLINE]
	,[WASTE_DEGREE_OF_CERTAINTY]
	,[WASTE_COSTCOUNT_FLAG]
	,[WASTE_DESCRIPTION]
	,[WASTE_IPSOURCE]
	,[WASTE_SpecialtySocietyLabel]
	,[WASTE_MeasureFamilyPopulationAge]
	,[WASTE_MillimanConsolidatedSpecialistId]
	,[WASTE_MillimanConsolidatedSpecialistDescription]
	,[WASTE_MillimanSpecialistPCPMap]
	,[WASTE_MeasureFamilyPopulationGender]
	,[WASTE_MeasureFamilyRootCause]
	,[WASTE_MeasureFamilyWCTopicalThemes]
	,[PRVDR_OSCAR_NUM]
	,[PRVDR_OSCAR_NAME]
INTO
	mi_ATM945_ACOI.dbo.dat_Claims
FROM
	mi_ATM945_ACOI.dbo.dat_Claims_p as a
	left join mi_ATM945_ACOI.dbo.tmpref_hospice_clm_type_claim_id as c
		on a.[CLAIM_ID] = c.[CUR_CLM_UNIQ_ID]
GO



/*
Caution: Changing any part of an object name could break scripts and stored procedures.

(61239104 row(s) affected)

*/

/*
USE mi_ATM945_ACOI
GO
IF (OBJECT_ID('mi_ATM945_ACOI.dbo.dat_Claims_p', 'U') IS NOT NULL
	AND (SELECT SUM (row_count) FROM sys.dm_db_partition_stats WHERE object_id=OBJECT_ID('dat_Claims_p') AND (index_id=0 or index_id=1)) = (SELECT SUM (row_count) FROM sys.dm_db_partition_stats WHERE object_id=OBJECT_ID('dat_Claims') AND (index_id=0 or index_id=1))
	AND (SELECT SUM (row_count) FROM sys.dm_db_partition_stats WHERE object_id=OBJECT_ID('dat_Claims') AND (index_id=0 or index_id=1)) <> 0
	)
DROP TABLE mi_ATM945_ACOI.dbo.dat_Claims_p;
*/
